sudo: required
services:
  - docker

before_install:
  - docker build -t shivi30sharma/docker-react -f Dockerfile.dev .   


script:
  - docker run shivi30sharma/docker-react npm run test -- --coverage     